# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory to /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN yarn install --quiet

# Bundle app source
COPY . .

# Expose port 3000 to the outside world
EXPOSE 3000

# Start the application
CMD ["yarn", "run", "dev"]
