import MainLayout from "@/layouts/MainLayout";
import Image from "next/image";

import img1 from "../public/images/img1.jpg";
import evidence from "../public/images/evidence.jpg";
import causes from "../public/images/causes.jpg";
import effects from "../public/images/effects.webp";
import solutions from "../public/images/solutions.jpg";

import { IoMailOutline } from "react-icons/io5";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function App() {
  return (
    <MainLayout>
      <section
        id="section1"
        className="w-full h-screen flex justify-center items-center"
      >
        <p
          id="quotes"
          className="w-full h-full flex justify-center items-center text-2xl text-white font-semibold px-6"
        >
          {/* TODO: this should be randomized quotes from backend */}
          Climate change is no longer some far-off problem
          <br />
          it is happening here, it is happening now.
        </p>
      </section>
      <section id="section2" className="pt-4">
        <h1 className="text-white text-center font-semibold text-xl">
          About Us
        </h1>
        <div className="grid p-6 gap-5 md:grid-cols-2">
          <div>
            <div className="flex flex-col justify-center md:p-8 md:pb-0 text-white">
              <p className="text-lg py-3 md:text-base font-semibold flex items-center">
                OUR MISSION
              </p>
              <p className="text-xs">
                Climate change is the greatest threat to humanity, perhaps ever.
                Global temperatures are rising at an unprecedented rate, causing
                drought and forest fires and impacting human health.
              </p>
            </div>
            <div className="flex flex-col justify-center md:p-8 md:pt-0 text-white">
              <p className="text-lg py-3 md:text-base font-semibold flex items-center">
                OUR VISION
              </p>
              <p className="text-xs">
                The environment is where we all meet; where we all have a mutual
                interest it is the one thing all of us share.
              </p>
            </div>
          </div>
          <Image src={img1} alt="about1" className="" />
        </div>
      </section>
      <section id="section3" className="p-6">
        <h1 className="text-white font-semibold text-xl">News and Features</h1>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-white text-xs">
          <div>
            <Image src={img1} alt="about1" className="" />
            <div className="py-2">
              <span className="font-semibold text-gray-500">NEWS</span>
              <p className="py-2">
                Global Call to Action: Unprecedented Climate Change Challenges
                Demand Urgent Solutions
              </p>
            </div>
          </div>
          <div>
            <Image src={img1} alt="about1" className="" />
            <div className="py-2">
              <span className="font-semibold text-gray-500">NEWS</span>
              <p className="py-2">
                Global Call to Action: Unprecedented Climate Change Challenges
                Demand Urgent Solutions
              </p>
            </div>
          </div>
          <div>
            <Image src={img1} alt="about1" className="" />
            <div className="py-2">
              <span className="font-semibold text-gray-500">NEWS</span>
              <p className="py-2">
                Global Call to Action: Unprecedented Climate Change Challenges
                Demand Urgent Solutions
              </p>
            </div>
          </div>
        </div>
      </section>
      <section id="section4" className="py-6">
        <h1 className="text-white text-center font-semibold text-4xl mb-12">
          Apa itu Climate Change?
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-2">
          <div className="text-white relative">
            <Image src={evidence} alt="evidence" id="evidence" style={{minHeight: "350px", objectFit: "cover"}} />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/evidence"
            >
              <h2 className="font-bold text-xs py-4">EVIDENCE</h2>
              <p className="font-bold">
                How Do We Know <br /> Climate Change Is Real?
              </p>
            </a>
          </div>
          <div className="text-white relative">
            <Image src={causes} alt="causes" id="evidence" style={{minHeight: "350px", objectFit: "cover"}} />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/causes"
            >
              <h2 className="font-bold text-xs py-4">CAUSES</h2>
              <p className="font-bold">
                Why is Climate Change <br /> Happening?
              </p>
            </a>
          </div>
          <div className="text-white relative">
            <Image src={effects} alt="effects" id="evidence" />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/effects"
            >
              <h2 className="font-bold text-xs py-4">EFFECTS</h2>
              <p className="font-bold">
                What are the effects of  <br /> Climate Change?
              </p>
            </a>
          </div>
          <div className="text-white relative">
            <Image src={solutions} alt="solutions" id="evidence" />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/solutions"
            >
              <h2 className="font-bold text-xs py-4">SOLUTIONS</h2>
              <p className="font-bold">
                What is Being Done to <br /> Solve Climate Change?
              </p>
            </a>
          </div>
        </div>
      </section>
      <section id="section5" className="text-white">
        <div className="grid md:grid-flow-col md:grid-cols-2 justify-center items-center h-150px bg-slate-950 pb-5">
          <div className="flex flex-col p-4 md:px-10">
            <h1 className="text-xl font-bold">Get in touch with us</h1>
            <p className="text-xs">Subscribe for more updated informations</p>
          </div>
          <div className="join md:px-4">
            <div className="btn text-lg text-white bg-black rounded-l-full">
              <IoMailOutline />
            </div>
            <input
              className="input input-bordered join-item text-black"
              placeholder="Email"
              type="email"
            />
            <button className="btn join-item rounded-r-full bg-black text-white">Subscribe</button>
          </div>
        </div>
      </section>
    </MainLayout>
  );
}
