"use client";
import { useEffect, useState } from "react";

import MainLayout from "@/layouts/MainLayout";
import Image from "next/image";
import CardsList from "@/components/CardsList";

import axios from "axios";

import img1 from "../public/images/img1.jpg";
import evidence from "../public/images/evidence.jpg";
import causes from "../public/images/causes.jpg";
import effects from "../public/images/effects.webp";
import solutions from "../public/images/solutions.jpg";

import { IoMailOutline } from "react-icons/io5";

import AOS from "aos";
import "aos/dist/aos.css";

// export const metadata = {
//   title: "Home",
//   description: "Generated by create next app",
// };

export default function App() {
  const [news, setNews] = useState([]);
  const dotenv = require("dotenv");
  dotenv.config();
  const API_KEY = process.env.NEXT_PUBLIC_API_KEY || "";
  const API_URL = process.env.NEXT_PUBLIC_BASE_URL || "";
  const NEWS_API = `${API_URL}${API_KEY}`;

  const [currentPage, setCurrentPage] = useState(1);
  const rowsPerPage = 3;
  const lastIndex = currentPage * rowsPerPage;
  const firstIndex = lastIndex - rowsPerPage;
  const rows = news.slice(firstIndex, lastIndex);
  const npage = Math.ceil(news.length / rowsPerPage);
  const numbers = [...Array(npage + 1).keys()].slice(1);

  const prevPage = () => {
    if (currentPage !== firstIndex) {
      setCurrentPage(currentPage - 1);
    }
  };
  const nextPage = () => {
    if (currentPage !== lastIndex) {
      setCurrentPage(currentPage + 1);
    }
  };
  const changeCurPage = (number) => {
    setCurrentPage(number);
  };

  // init library AOS
  useEffect(() => {
    AOS.init({
      easing: "ease-out-cubic",
      offset: 50,
      duration: 1000,
    });
  }, []);

  const getNews = async () => {
    const response = await axios.get(`${NEWS_API}`);
    const responseJson = await response.data.articles;
    setNews(responseJson);
  };

  useEffect(() => {
    getNews();
  }, []);

  if (news.length <= 0) {
    return (
      <MainLayout>
        <section
          id="section1"
          className="w-full h-screen flex justify-center items-center"
        >
          <p
            id="quotes"
            className="w-full h-full flex justify-center items-center text-4xl text-white text-center font-semibold px-6"
            data-aos="fade-down"
          >
            {/* TODO: this should be randomized quotes from backend */}
            Climate change is no longer some far-off problem
            <br />
            it is happening here, it is happening now.
          </p>
        </section>
        <section id="section2" className="pt-4">
          <h1
            className="text-white text-center font-semibold text-3xl"
            data-aos="fade-up"
          >
            About Us
          </h1>
          <div className="grid p-6 gap-5 md:grid-cols-2" data-aos="fade-up">
            <div>
              <div className="flex flex-col justify-center md:p-8 md:pb-0 text-white">
                <p className="text-lg py-3 md:text-2xl font-semibold flex items-center">
                  OUR MISSION
                </p>
                <p className="text-base md:text-lg">
                  Climate change is the greatest threat to humanity, perhaps
                  ever. Global temperatures are rising at an unprecedented rate,
                  causing drought and forest fires and impacting human health.
                </p>
              </div>
              <div className="flex flex-col justify-center md:p-8 md:pt-0 text-white">
                <p className="text-lg py-3 md:text-2xl font-semibold flex items-center">
                  OUR VISION
                </p>
                <p className="text-base md:text-lg">
                  The environment is where we all meet; where we all have a
                  mutual interest it is the one thing all of us share.
                </p>
              </div>
            </div>
            <Image src={img1} alt="about1" className="" />
          </div>
        </section>
        <section id="section3" className="p-6">
          <h1 className="text-white font-semibold text-lg md:text-2xl">
            News and Features
          </h1>
          <div
            className="grid grid-cols-2 md:grid-cols-3 gap-4 text-white text-base"
            data-aos="fade-left"
          >
            <div>
              <Image src={img1} alt="about1" className="" />
              <div className="py-2">
                <span className="font-semibold text-gray-500">NEWS</span>
                <p className="py-2">
                  Global Call to Action: Unprecedented Climate Change Challenges
                  Demand Urgent Solutions
                </p>
              </div>
            </div>
            <div>
              <Image src={img1} alt="about1" className="" />
              <div className="py-2">
                <span className="font-semibold text-gray-500">NEWS</span>
                <p className="py-2">
                  Global Call to Action: Unprecedented Climate Change Challenges
                  Demand Urgent Solutions
                </p>
              </div>
            </div>
            <div>
              <Image src={img1} alt="about1" className="" />
              <div className="py-2">
                <span className="font-semibold text-gray-500">NEWS</span>
                <p className="py-2">
                  Global Call to Action: Unprecedented Climate Change Challenges
                  Demand Urgent Solutions
                </p>
              </div>
            </div>
          </div>
        </section>
        <section id="section4" className="py-6">
          <h1
            className="text-white text-center font-semibold text-4xl md:text-5xl mb-12"
            data-aos="fade-up"
          >
            Apa itu Climate Change?
          </h1>
          <div className="grid grid-cols-1 md:grid-cols-2 text-xl">
            <div className="text-white relative" data-aos="zoom-in">
              <Image
                src={evidence}
                alt="evidence"
                id="evidence"
                style={{ minHeight: "500px", objectFit: "cover" }}
              />
              <a
                className="absolute text-center w-full h-full flex flex-col justify-center"
                id="textOverlay"
                href="/education/evidence"
              >
                <h2 className="font-bold text-xl py-2">EVIDENCE</h2>
                <p className="font-bold text-3xl">
                  How Do We Know <br /> Climate Change Is Real?
                </p>
              </a>
            </div>
            <div className="text-white relative" data-aos="zoom-in">
              <Image
                src={causes}
                alt="causes"
                id="evidence"
                style={{ minHeight: "500px", objectFit: "cover" }}
              />
              <a
                className="absolute text-center w-full h-full flex flex-col justify-center"
                id="textOverlay"
                href="/education/causes"
              >
                <h2 className="font-bold text-xl py-2">CAUSES</h2>
                <p className="font-bold text-3xl">
                  Why is Climate Change <br /> Happening?
                </p>
              </a>
            </div>
            <div className="text-white relative" data-aos="zoom-in">
              <Image
                src={effects}
                alt="effects"
                id="evidence"
                style={{ minHeight: "500px", objectFit: "cover" }}
              />
              <a
                className="absolute text-center w-full h-full flex flex-col justify-center"
                id="textOverlay"
                href="/education/effects"
              >
                <h2 className="font-bold text-xl py-2">EFFECTS</h2>
                <p className="font-bold text-3xl">
                  What are the effects of <br /> Climate Change?
                </p>
              </a>
            </div>
            <div className="text-white relative" data-aos="zoom-in">
              <Image
                src={solutions}
                alt="solutions"
                id="evidence"
                style={{ minHeight: "500px", objectFit: "cover" }}
              />
              <a
                className="absolute text-center w-full h-full flex flex-col justify-center"
                id="textOverlay"
                href="/education/solutions"
              >
                <h2 className="font-bold text-xl py-2">SOLUTIONS</h2>
                <p className="font-bold text-3xl">
                  What is Being Done to <br /> Solve Climate Change?
                </p>
              </a>
            </div>
          </div>
        </section>
        <section id="section5" className="text-white">
          <div className="grid md:grid-flow-col md:grid-cols-2 justify-center items-center h-150px bg-slate-950 pb-5">
            <div className="flex flex-col p-4 md:ps-10">
              <h1 className="text-3xl font-bold">Get in touch with us</h1>
              <p className="text-base">
                Subscribe for more updated informations
              </p>
            </div>
            <div className="join md:px-4">
              <div className="btn text-lg text-white bg-black rounded-l-full">
                <IoMailOutline />
              </div>
              <input
                className="input input-bordered join-item text-black"
                placeholder="Email"
                type="email"
              />
              <button className="btn join-item rounded-r-full bg-black text-white">
                Subscribe
              </button>
            </div>
          </div>
        </section>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <section
        id="section1"
        className="w-full h-screen flex justify-center items-center"
      >
        <p
          id="quotes"
          className="w-full h-full flex justify-center items-center text-4xl text-white text-center font-semibold px-6"
          data-aos="fade-down"
        >
          {/* TODO: this should be randomized quotes from backend */}
          Climate change is no longer some far-off problem
          <br />
          it is happening here, it is happening now.
        </p>
      </section>
      <section id="section2" className="pt-4">
        <h1
          className="text-white text-center font-semibold text-3xl"
          data-aos="fade-up"
        >
          About Us
        </h1>
        <div className="grid p-6 gap-5 md:grid-cols-2" data-aos="fade-up">
          <div>
            <div className="flex flex-col justify-center md:p-8 md:pb-0 text-white">
              <p className="text-lg py-3 md:text-2xl font-semibold flex items-center">
                OUR MISSION
              </p>
              <p className="text-base md:text-lg">
                Climate change is the greatest threat to humanity, perhaps ever.
                Global temperatures are rising at an unprecedented rate, causing
                drought and forest fires and impacting human health.
              </p>
            </div>
            <div className="flex flex-col justify-center md:p-8 md:pt-0 text-white">
              <p className="text-lg py-3 md:text-2xl font-semibold flex items-center">
                OUR VISION
              </p>
              <p className="text-base md:text-lg">
                The environment is where we all meet; where we all have a mutual
                interest it is the one thing all of us share.
              </p>
            </div>
          </div>
          <Image src={img1} alt="about1" className="" />
        </div>
      </section>
      <section id="section3" className="p-6">
        <h1 className="text-white font-semibold text-lg md:text-4xl">
          News and Features
        </h1>
        <div
          className="grid grid-cols-2 md:grid-cols-3 gap-2 text-white text-base p-2 md:p-10"
          data-aos="fade-right"
        >
          <CardsList newsArr={rows} />
        </div>
          <nav className="flex justify-center">
            <ul className="flex flex-wrap justify-center gap-1">
              <li className="join-item btn border border-slate-300 bg-black text-white">
                <a href="#" className="page-link " onClick={prevPage}>
                  Prev
                </a>
              </li>
              {numbers.map((number, idx) => {
                return (
                  <li
                    className={`join-item btn border border-slate-300 bg-black text-white ${
                      currentPage === number ? "active" : ""
                    }`}
                    key={idx}
                  >
                    <a
                      href="#"
                      className="page-link"
                      onClick={() => changeCurPage(number)}
                    >
                      {number}
                    </a>
                  </li>
                );
              })}
              <li className="join-item btn border border-slate-300 bg-black text-white">
                <a href="#" className="page-link" onClick={nextPage}>
                  Next
                </a>
              </li>
            </ul>
          </nav>
      </section>
      <section id="section4" className="py-6">
        <h1
          className="text-white text-center font-semibold text-4xl md:text-5xl mb-12"
          data-aos="fade-up"
        >
          Apa itu Climate Change?
        </h1>
        <div className="grid grid-cols-1 md:grid-cols-2 text-xl">
          <div className="text-white relative" data-aos="zoom-in">
            <Image
              src={evidence}
              alt="evidence"
              id="evidence"
              style={{ minHeight: "500px", objectFit: "cover" }}
            />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/evidence"
            >
              <h2 className="font-bold text-xl py-2">EVIDENCE</h2>
              <p className="font-bold text-3xl">
                How Do We Know <br /> Climate Change Is Real?
              </p>
            </a>
          </div>
          <div className="text-white relative" data-aos="zoom-in">
            <Image
              src={causes}
              alt="causes"
              id="evidence"
              style={{ minHeight: "500px", objectFit: "cover" }}
            />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/causes"
            >
              <h2 className="font-bold text-xl py-2">CAUSES</h2>
              <p className="font-bold text-3xl">
                Why is Climate Change <br /> Happening?
              </p>
            </a>
          </div>
          <div className="text-white relative" data-aos="zoom-in">
            <Image
              src={effects}
              alt="effects"
              id="evidence"
              style={{ minHeight: "500px", objectFit: "cover" }}
            />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/effects"
            >
              <h2 className="font-bold text-xl py-2">EFFECTS</h2>
              <p className="font-bold text-3xl">
                What are the effects of <br /> Climate Change?
              </p>
            </a>
          </div>
          <div className="text-white relative" data-aos="zoom-in">
            <Image
              src={solutions}
              alt="solutions"
              id="evidence"
              style={{ minHeight: "500px", objectFit: "cover" }}
            />
            <a
              className="absolute text-center w-full h-full flex flex-col justify-center"
              id="textOverlay"
              href="/education/solutions"
            >
              <h2 className="font-bold text-xl py-2">SOLUTIONS</h2>
              <p className="font-bold text-3xl">
                What is Being Done to <br /> Solve Climate Change?
              </p>
            </a>
          </div>
        </div>
      </section>
      <section id="section5" className="text-white">
        <div className="grid md:grid-flow-col md:grid-cols-2 justify-center items-center h-150px bg-slate-950 pb-5">
          <div className="flex flex-col p-4 md:ps-10">
            <h1 className="text-3xl font-bold">Get in touch with us</h1>
            <p className="text-base">Subscribe for more updated informations</p>
          </div>
          <div className="join md:px-4">
            <div className="btn text-lg text-white bg-black rounded-l-full">
              <IoMailOutline />
            </div>
            <input
              className="input input-bordered join-item text-black"
              placeholder="Email"
              type="email"
            />
            <button className="btn join-item rounded-r-full bg-black text-white">
              Subscribe
            </button>
          </div>
        </div>
      </section>
    </MainLayout>
  );
}
